### ISSUE TITLE
Checklist for win-arm64 support

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#11090]
### Description

- [x] Merge arcade update: https://github.com/xamarin/yaml-templates/pull/204
- [x] Set `SupportsMachineArch=true`:
  - [x] https://github.com/xamarin/xamarin-android/pull/7471
  - [x] https://github.com/xamarin/xamarin-macios/pull/16935
  - [x] https://github.com/dotnet/maui/pull/11803
- [x] Build packages for .NET 6 and .NET 7
  - [x] xamarin/xamarin-android
  - [x] xamarin/xamarin-macios
  - [x] dotnet/maui
- [x] Create a VS insertion PR

### Usage Scenarios

Windows arm64 devices

**Comment by jonathanpeppers** [comment]
VS Insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/440414

We can probably close this when we find out if it is working (or merged).

**Comment by nCastle1** [comment]
With the latest VS preview 17.6p2, MAUI seems to be broken again on ARM64. The build refers to nuget packages that aren't available, and I can't find a way to configure this behavior.

This occurs with existing MAUI projects as well as new projects created from the template.

![image](https://user-images.githubusercontent.com/29742178/225171866-6efd8fa5-685e-4af2-9a32-c3b0b6e31ade.png)

**Comment by jonathanpeppers** [comment]
@dalexsoto should the above packages be on NuGet.org already?

**Comment by dalexsoto** [comment]
Weird, I am sure why it is asking for that version, AFAIK we did not participate in P2 I'll investigate

**Comment by dalexsoto** [comment]
@nCastle1 this should be fixed now, please try again.

**Comment by jonathanpeppers** [comment]
In general, we shipped Windows ARM64 support in 17.6. I think we can close this now.

**Comment by jfversluis** [comment]
Closing for now, seems this is complete and I've been using it successfully for a while!
