### ISSUE TITLE
As a desktop developer I can support advanced keyboard interactions

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#14021]
### Tasks

- [ ] [Menu missing accelerators](http://github.com/dotnet/maui/issues/5211)
- [ ] [Proposal: mouse and keyboard classes](http://github.com/dotnet/maui/issues/3739)
- [ ] [Tab button doesn't work when shift button last used](http://github.com/dotnet/maui/issues/7064)
- [ ] [Tab key moves through fields on Mac Catalyst](http://github.com/dotnet/maui/issues/8473)
- [ ] [Additional desktop features](https://github.com/dotnet/maui/issues/9139)
