### ISSUE TITLE
Reconcile Essentials API's with MAUI

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#1965]
Historically Xamarin.Essentials and Forms had similar API's doing the same things, but because they were never in the same package, they were both necessary.

We need to reconcile this and move API's or change their implementation to use a common base.  After an initial call we identified these API's which need attention:

## Device
- [x] #4478 and #2651
- [x] `Device.FlowDirection` - https://github.com/dotnet/maui/pull/4936
- [x] `Idiom` https://github.com/dotnet/maui/pull/4548
- [x] `RuntimePlatform` https://github.com/dotnet/maui/pull/4548   
- [x] #4479
- [x] Info - obsolete (hidden) #3213

### Move these to Window, use Application.Windows.First() to back these and obsolete them:
- [x] IsInvokeRequired #2862
- [x] BeginInvokeOnMainThread(Action) #2862
- [x] GetMainThreadSynchronizationContextAsync #2862
- [x] InvokeOnMainThreadAsync(Func<T>) #2862
- [x] InvokeOnMainThreadAsync(Action) #2862
- [x] InvokeOnMainThreadAsync(Func<Task<T>>) #2862
- [x] InvokeOnMainThreadAsync(Func<Task>) #2862

## PlatformServices
- [x] RequestedTheme - https://github.com/dotnet/maui/pull/4964
- [x] GetHash - remove https://github.com/dotnet/maui/pull/2707
- [x] GetMD5Hash - remove https://github.com/dotnet/maui/pull/2707
- [x] #4492
- [x] #4570
- [x] GetPlatformSize - https://github.com/dotnet/maui/pull/4885
- [x] GetStreamAsync - remove https://github.com/dotnet/maui/pull/2710
- [x] GetUserStoreForApplication - remove https://github.com/dotnet/maui/pull/2710
- [x] OpenUriAction - obsolete, use essentials #2651
- [x] QuitApplication - move to application #2653
- [x] StartTimer - https://github.com/dotnet/maui/pull/4944

Application
- [x] Dispatcher - find window of mainpage and use that dispatcher  #2862
- [x] MainPage / CreateWindow  
      Make CreateWindow return MainPage, if no mainpage is set throw
      Set MainPage, go through windows to find window with current mainpage, and replace mainpage 
 - [x] GetMainThreadSynchronizationContextAsync #2862

**Comment by mattleibow** [comment]
Finally ready to close!!! Was nice knowing you IPlatformServices!
