### ISSUE TITLE
Epic: Add new SetBinding API for defining "compiled" bindings in code

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/maui#22384]
We agreed to implement a new public API to allow creating "compiled" bindings (`TypedBinding<TSource, TProperty>`) in code via source-generators and interceptors based on the proposal https://github.com/dotnet/maui/issues/20574 (see _Alternative design_).

- [x] Introduce new public method `BindableObjectExtensions.SetBinding<TSource, TProperty>(BindableProperty property, Func<TSource, TProperty> getter, ...)` as defined in the proposal
- [x] Create a new source generator
    - [x] Intercept calls to `SetBinding<TSource, TProperty>(...)`
    - [x] Parse getter lambda expression
        - [x] Implement support for properties
        - [x] Implement support for indexers
        - [x] Implement support for `as`-casts
        - [x] Implement support for C-style casts
        - [x] Implement support for conditional access to members
        - [x] Implement diagnostics reporting
        - [x] Build cacheable data model
    - [x] Generate setter from the getter lambda
    - [x] Generate handlers array from the getter lambda
- [x] Enable the source generator by default in MAUI apps
    - [x] Introduce a feature switch to disable the source generator
- [x] Add unit tests for correct caching of the generated code 
- [x] Run benchmarks comparing reflection-based binding, source-generated binding, and hand-written typed binding
- [ ] ~Write docs/developer guide~ - tracked in https://github.com/dotnet/docs-maui/issues/2304

## Possible future improvements

- [x] Replace usage of `TypedBinding.ForSingleNestingLevel(...)` with the source generated interceptors - https://github.com/dotnet/maui/pull/23393
- [ ] Implement support for generic parameters
- [x] Use the new overload in existing unit tests
- [x] Add more public methods that could be intercepted (this has not been discussed/agreed on yet) - https://github.com/dotnet/maui/pull/23239
    - for example:
        - `BindingBase Binding.Create<TSource, TProperty>(Func<TSource, TProperty> getter, ...)`
        - `TBindable Bind<TBindable, TSource, TProperty>(this TBindable bindableObject, Func<TSource, TProperty> getter, ...) where TBindable : BindableObject`.
- [ ] Improve efficiency by grouping calls to `SetBinding` with the same `getter` signature into one interceptor
- [x] Split individual generated methods into separate files for more granular caching - https://github.com/dotnet/maui/pull/23116
- [ ] Explore the option of resolving method groups instead of just lambda expressions
- [ ] Use roslyn-sdk test library

**Comment by AmrAlSayed0** [comment]
In this proposal [#20574](20574), the generated method `StudentFirstNameBinding` could benefit from being generic. So instead of this
```csharp
partial class StudentDetailPage
{
    private static BindingBase StudentFirstNameBinding(
        object? source = null,
        BindingMode mode = BindingMode.OneWay, // default value based on the attribute value
        IValueConverter? converter = null,
        object? converterParameter = null,
        string? stringFormat = null,
        object? targetNullValue = null,
        object? fallbackValue = null)
        => ...;
}
```
it would be this
```csharp
partial class StudentDetailPage
{
    private static BindingBase StudentFirstNameBinding<TSource, TProperty>(
        TSource? source = null,
        BindingMode mode = BindingMode.OneWay, // default value based on the attribute value
        IValueConverter? converter = null,
        object? converterParameter = null,
        [System.Diagnostics.CodeAnalysis.StringSyntax] string? stringFormat = null,
        TProperty? targetNullValue = null,
        TProperty? fallbackValue = null)
        => ...;
}
```
Same thing with `SetBinding`
```csharp
public static partial class BindableObjectExtensions
{
    public static void SetBinding<TSource, TProperty>(
        this TSource self,
        BindableProperty property,
        Func<TSource, TProperty> getter,
        Action<TSource, TProperty>? setter = null,
	BindingMode mode = BindingMode.Default,
	IValueConverter? converter = null,
	object? converterParameter = null,
	[System.Diagnostics.CodeAnalysis.StringSyntax] string? stringFormat = null,
	object? source = null,
	TProperty? fallbackValue = null,
	TProperty? targetNullValue = null) where TSource : BindableObject
    {
        throw new InvalidOperationException($"The method call to {nameof(SetBinding<TSource, TProperty>)} was not intercepted.");
    }
}
```
Also, would it be useful to think about introducing a generic `IValueConverter<TFrom, TTo>` or even `IValueConverter<TFrom, TTo, TParameter>`? I know that converters are often used to convert from multiple value types but if there is a use case that only needs to convert from one type then this allows more types to flow through the linker's analysis and hopefully not trim out the types. I don't think that following the outdated Interface of the WPF days is useful here.


Finally, keep up the good work 💪
