### ISSUE TITLE
Epic: Blazor developers can target and deploy their applications to desktop platforms, allowing them to run natively

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/maui#2536]
### Summary

In .NET 6 we want to extend Blazor's target scenarios to include native desktop applications via web-based rendering.

> Note: This is a proposed experience for .NET 6 and not yet committed.

### User Stories

User Stories under this Epic:

- [x] [Reuse existing Blazor components from a web app in a Blazor hybrid desktop app](https://github.com/dotnet/aspnetcore/issues/27235)
- [x] [Create a single project Blazor hybrid desktop app project from the .NET CLI or from Visual Studio](https://github.com/dotnet/aspnetcore/issues/27229).
- [x] [Build, run, debug Blazor hybrid desktop apps using the development platform](https://github.com/dotnet/aspnetcore/issues/27233)
- [x] [Use native controls alongside web-rendered UI in a Blazor hybrid desktop app](https://github.com/dotnet/aspnetcore/issues/27239)
- [x] [Light-up platform specific functionality in individual Blazor components in a Blazor hybrid desktop app](https://github.com/dotnet/aspnetcore/issues/27236)
- [ ] [Create installable artifacts for Blazor hybrid desktop apps for Windows, macOS, and Linux](https://github.com/dotnet/aspnetcore/issues/27234)
- [ ] [Xamarin/Blazor developers can target macOS with .NET 6](https://github.com/dotnet/runtime/issues/44736)

**Comment by Eilon** [comment]
Closing this because most of this works by now, and everything else should be tracked with various bugs marked as `area/blazor`: https://github.com/dotnet/maui/issues?q=is%3Aopen+is%3Aissue+label%3A%22area%2Fblazor+%F0%9F%95%B8%EF%B8%8F%22
