### ISSUE TITLE
Enhance TypeConverter usage and caching

### ISSUE THREAD

**Issue by StephaneDelcroix** [dotnet/maui#5660]
### Description

(this issue is a tracker for a discussion that happened here: https://github.com/dotnet/maui/pull/5655#discussion_r838211186)

Type Conversion happens at multiple places:
- when setting a value from xaml
- when applying a binding (this includes AppThemeBinding, DynamicResource, ...)
- when applying a style

We currently have multiple allow lists for TypeConverter: TypeConversionExtensions.KnownConverters, TCE.KnownConverterFactories, BindableProperty.KnownTypeConverter; and then we have NodeILExtensions.KnonwnCompiledTypeConverters

@jonathanpeppers asked if converters for `Color` or `Thickness` require to be allow-listed (https://github.com/jonathanpeppers): ColorTypeConverter and ThicknessTypeConverter do _not_ need to be cached in a known list, as they are attributed with a TypeConverterAttribute, they need to be in the KnownCOMPILEDTypeConverter as they're not attributed with the ProvideCompiledAttibute.

The only converter that can not be retrieved using reflection is UriTypeConverter as System.Uri is NOT attributed on .NET core 6 (even though System provides a UriTypeConverter that we should use now that we replaced our own base TypeConverter type by System.ComponentModel.TypeConverter. Side note, System.Uri is attributed in the net framework profile, go figure). so why do we allow-list ColorTypeConverter and EasingTypeConverter in BindableProperty.cs is something that need clarification.

I don't recall the details of why FontTypeConverter need to be allow-listed, but I recall that we almost got rid of Font as a property type in most (all?) of our controls (because compound properties are a mess and produce too many propertychange events, and redraw).

We could/should cache the TypeConverters:
- at runtime when we encounter them
- at startup time using reflection (fuck no)
- or at compile time using a sourcegen
Our own TypeConverters are known beforehand, but I'm not keen on maintaining a list of those (I'd prefer a sourcegen), but there's also the TypeConverters defined in 3rd party assemblies. Oh, and caching type converters isn't a solution for avoiding reflection, as TypeConverterAttributes on properties take priority over the ones defined on Type, but we could cache that too (using the PropertyInfo as key e.g.)

Here's a list of action points:
- [x] Investigate the usage of `Font` in Controls. It's probably unused, in that case `FontTypeConverter` and the 2 caches in TypeConversionExtension could go away: #5664 
- [ ] Investigate `Font` usage in Core, and the reason it was ported there, and not deprecated
- [x] Investigate why ColorTypeConverter and EasingTypeConverter are allow-listed: #5670
- [ ] Investigate caching TypeConverters for properties and types. I'd recommend going for a sourcegen solution and generate a switch instead of a dictionary to avoid allocation bump (#5655 enable runtime caching)
- [ ] None of our TypeConverters have any side effect, and instances could be reused (we can speak for 3rd party converters, unfortunately...) (#5655 reuses instance. we need to agree if we're ok with that (I am))
- [ ] Use TypeDescriptor.GetConverter for native conversions, including Uri (https://github.com/dotnet/runtime/blob/4ed3063d8bc434fd29fe63cf093c17baa9ff8fd3/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L180)
- [ ] As TypeConverters only convert from strings, bypass converter lookup if input type isn't string

### (Public) API Changes

/

**Comment by mattleibow** [comment]
@StephaneDelcroix is this still an issue or are we done?
