### ISSUE TITLE
Determine which Essentials work in Windows Unpackaged apps

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#8552]
### Description

Not all Essentials APIs are working in **Unpackaged** windows apps. We need to add device tests to the Essentials.DeviceTests project for everything in the list below. For anything that does not currently work in a Windows unpackaged app, we'll need to open an issue. Note that you can switch between packaged/unpackaged by modifying Essentials.DeviceTests.csproj (instructions are in the csproj comments).

Once you've merged a device test for a feature (and created an issue if necessary), please check it off below.

 - [x] Accessibility.SemanticScreenReader
 - [x] ApplicationModel.AppActions
 - [x] ApplicationModel.AppInfo  (#8536)
 - [x] ApplicationModel.Browser
 - [x] ApplicationModel.Communication.Contacts _(partially)_   
       - GetAllAsync works
       - PickContactAsync throws
       - Bug: https://github.com/microsoft/WindowsAppSDK/issues/1157)
 - [x] ApplicationModel.Communication.Email  
       - Workaround: https://github.com/dotnet/maui/pull/10063
       - Bug: https://github.com/microsoft/WindowsAppSDK/issues/3433)
 - [x] ApplicationModel.Communication.PhoneDialer
       - Bug: https://github.com/microsoft/WindowsAppSDK/issues/3003
 - [x] ApplicationModel.Communication.Sms
       - Bug: https://github.com/microsoft/WindowsAppSDK/issues/3014
 - [x] ApplicationModel.DataTransfer.Clipboard
 - [x] ApplicationModel.DataTransfer.Share
 - [x] ApplicationModel.Launcher
 - [x] ApplicationModel.MainThread
 - [x] ApplicationModel.Map
 - [x] ApplicationModel.Permissions
      - Fixes: https://github.com/dotnet/maui/pull/10477
 - [x] ApplicationModel.VersionTracking
 - [x] ApplicationModel.WindowStateManager
 - [x] ~Authentication.AppleSignInAuthenticator~ _(Not a Windows feature)_
 - [x] Authentication.WebAuthenticator  (https://github.com/microsoft/WindowsAppSDK/issues/441)
 - [x] Devices.Battery
 - [x] Devices.DeviceDisplay
 - [x] Devices.DeviceInfo
 - [ ] Devices.Flashlight
 - [ ] Devices.HapticFeedback
 - [ ] Devices.Sensors.Accelerometer
 - [ ] Devices.Sensors.Barometer
 - [ ] Devices.Sensors.Compass
 - [x] Devices.Sensors.Geocoding
 - [x] Devices.Sensors.Geolocation
 - [ ] Devices.Sensors.Gyroscope
 - [ ] Devices.Sensors.Magnetometer
 - [ ] Devices.Sensors.OrientationSensor
 - [ ] Devices.Vibration
 - [x] Media.MediaPicker _(partially)_
      - Picker works 
      - Capture has workaround https://github.com/dotnet/maui/pull/13220
      - Bug: https://github.com/microsoft/WindowsAppSDK/issues/3241
      - Bug: https://github.com/microsoft/WindowsAppSDK/issues/1034
 - [x] Media.Screenshot
 - [x] Media.TextToSpeech_(partially)_   
      - Speaking happens, but can't control the pitch
      - Bug: https://github.com/microsoft/WindowsAppSDK/issues/3015
 - [x] Media.UnitConverters
 - [x] Networking.Connectivity
 - [x] Storage.FilePicker
       - Workaround: https://github.com/dotnet/maui/pull/10356
       - Bug: https://github.com/dotnet/maui/issues/10313
 - [x] Storage.FileSystem  (#8536)
 - [x] Storage.Preferences (#8536)
 - [x] Storage.SecureStorage
      - Fixes: https://github.com/dotnet/maui/pull/10476

For tracking progress on PACKAGED apps: #8553

> VS bug [#1747285](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1747285)

**Comment by sinsedrix** [comment]
Does it mean it won't be possible to have unpackaged windows apps with .Net 6?

**Comment by mattleibow** [comment]
It does not. Just some windows apis have bugs that will be fixed when they release new versions of their nuget.

And, these bugs are very few - just the current open ones linked here.

**Comment by mattleibow** [comment]
Closing this now as most things are working. If there are any problems using some API then please open a new issue.

**Comment by sinsedrix** [comment]
Is "most things" enough? I still don't have images and fonts in the unpackaged app.

**Comment by janseris** [comment]
> Closing this now as most things are working. If there are any problems using some API then please open a new issue.

How can something be completed if 32/41 is completed. Your statement is effectively creating what's common in MAUI nowadays that the feature is not implemented and when someone needs it, they have to report is as bug because it's documented that it exists.

**Comment by mattleibow** [comment]
>  I still don't have images and fonts in the unpackaged app.

This is currently a bug in Win2D with _some_ fonts. We have a new issue here. I am working with the Win2D team to fix this and will open a new Win2D issue with a WinUI sample to help they resolve it sooner. However, _some_ fonts work, others do not.

Make sure that you are on the latest maui and you are also using Win2D 1.2.0+

The specific MAUI issue tracking the fonts is https://github.com/dotnet/maui/issues/21993

**Comment by mattleibow** [comment]
@janseris I am not sure what you mean by "32/41"?

**Comment by sinsedrix** [comment]
@mattleibow 
>This is currently a bug in Win2D with some fonts. We have a new issue here. I am working with the Win2D team to fix this and will open a new Win2D issue with a WinUI sample to help they resolve it sooner. However, some fonts work, others do not.
What about the images?

> Make sure that you are on the latest maui and you are also using Win2D 1.2.0+
I'm on maui-windows 8.0.21, I don't know where to set Wind2D version.
Will the font fix be also available for dotnet 7

**Comment by mattleibow** [comment]
I am not sure what you mean with images, but there were a bunch of issues with FontImageSource, the last of which we fixed here: https://github.com/dotnet/maui/pull/22646

This one was specifically for fonts with spaces in the family name. It has not yet been release and should be in the upcoming SR this month. 

The previous issue we fixed was in https://github.com/dotnet/maui/pull/20790.

This was a general fix for unpackaged and has been out since 8.0.10.

Both of these fixes need Win2D 1.2.0. We have updated the dependency in https://github.com/dotnet/maui/pull/21144 which was released in 8.0.20.

Since you are on 8.0.21, don't images should be working in unpackaged as long as your fonts don't have spaces in the font name.

With regards to net7, I don't think there will be any updates as I believe that is out of support. Maui, Android and iOS follow the STS support.
